// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB80xvQqvBRRwoM7ezGvGK6v7A8ZI1cu9w',
    appId: '1:177245132422:web:f4ee9ae94ce13489152307',
    messagingSenderId: '177245132422',
    projectId: 'deenroutine-64d95',
    authDomain: 'deenroutine-64d95.firebaseapp.com',
    storageBucket: 'deenroutine-64d95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZGKKytuQCKUy_NH13pGaq-VjjuFgBBM',
    appId: '1:177245132422:android:8ea8341027f02661152307',
    messagingSenderId: '177245132422',
    projectId: 'deenroutine-64d95',
    storageBucket: 'deenroutine-64d95.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEWvXO5Sj9meSqQ4x5GGAyqMSmj61uusY',
    appId: '1:177245132422:ios:444a6777e370c7e7152307',
    messagingSenderId: '177245132422',
    projectId: 'deenroutine-64d95',
    storageBucket: 'deenroutine-64d95.firebasestorage.app',
    iosBundleId: 'com.ZakiFaiaz.deenroutine',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEWvXO5Sj9meSqQ4x5GGAyqMSmj61uusY',
    appId: '1:177245132422:ios:531d042c4ebe2acb152307',
    messagingSenderId: '177245132422',
    projectId: 'deenroutine-64d95',
    storageBucket: 'deenroutine-64d95.firebasestorage.app',
    iosBundleId: 'com.example.deenroutine',
  );
}
